### PR TITLE
Add library.json for @PlatformIO

### PR DESCRIPTION
**Pull request by ivankravets**
Evaluate C/C++ Preprocessor conditional syntax

### CODE REVIEW

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/librarymanager/ldf.html#ldf-mode

PlatformIO does not evaluate C/C++ Preprocessor conditions by default for performance reason. Without this, it looks for all dependencies mentioned by `#include` directive. 

The alternative solution for PlatformIO users is adding `lib_ldf_mode = chain+` into `platformio.ini`. However, this manifest will do this for all projects.

**Comment by MCUdude** [comment]
I'm going to keep the commit aad4db4 because it has caused some issues in Arduino IDE as well. Do we need a separate library.json then?

**Comment by ivankravets** [comment]
Yes, we need `library.json`. It turns on C/C++ preprocessor for library dependency finder. Just only for this library.

**Comment by MCUdude** [comment]
So why don't we need it for the other libraries? and what about MiniCore?

**Comment by ivankravets** [comment]
Opss, stop! I see you removed it in https://github.com/MCUdude/MightyCore/commit/aad4db4b320e79fadd2cb2578c037f1d860d52c4 :) 

So, no need to do this.

**Comment by MCUdude** [comment]
Cool! So all that's left to do for me is to issue a new MightyCore release so we can get rid of this issue once and for all?

After this, are you going to remove the mightycore16 .. mightycore1284 board manifest files? They 're not needed anymore after a new release is available.

**Comment by ivankravets** [comment]
Yes, please file a new issue here https://github.com/platformio/platform-atmelavr/issues with these details to remove manifests and update cores. Thanks!

**Comment by MCUdude** [comment]
Thanks! Will do so when a new release is ready. Should only be a few days.

Slight offtopic:
Ever since I upgraded to PIO 4.0.0 it has become really slow, and it rebuilds all libraries and dependencies every time I want to compile or upload. Is this something that will be fixed in the next release, 4.0.1?

**Comment by ivankravets** [comment]
@MCUdude Oh... It should not! Could you try to switch to the latest RC via `pio upgrade --dev`. Does it work normal now?

**Comment by MCUdude** [comment]
Thanks! upgrading to 4.0.1rc2 pretty much doubled the build speed from 23.58s to 15.65s for a particular project.

**Comment by ivankravets** [comment]
@MCUdude does it rebuild full project when you do changes only in 1 src file?

**Comment by MCUdude** [comment]
After changing a single line in main.cpp it's now only rebuilding that particular file. However, PIO 4 feels much slower than PIO 3 did. When I click `build`  it's stuck at this line for about 9 seconds

```
Processing MightyCore (platform: atmelavr; framework: arduino; board: ATmega1284P)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

```

The project I used when building is a simple project for the ATmega1284P, and includes the Wire library. Compiled size is 3650 bytes. It still took 16.06 seconds to compile. That's actually slower than Arduino IDE.

**Comment by ivankravets** [comment]
Could you share a simple project or configuration to reproduce this issue? I have VM with Windows and want to check it. Thanks.

**Comment by MCUdude** [comment]
Sure! 
[Pio-test.zip](https://github.com/MCUdude/MightyCore/files/3519169/Pio-test.zip)

**Comment by ivankravets** [comment]
Which version of Python do you use? `python --version`? Do you use PlatformIO via PlatformIO IDE or as standalone CLI tool? If yes, how did you install it?

**Comment by MCUdude** [comment]
I'm using PlatformIO through VS Code. Nothing fancy at all. When running `python --version` from the shell (which is powershell BTW) I get `Python 2.7.13`.

**Comment by MCUdude** [comment]
@ivankravets are you able to reproduce the compile-time numbers I get?

**Comment by ivankravets** [comment]
For me, it "[SUCCESS] Took 3.21 seconds".

My machine is very slow, MacBook Pro 2010. Do you have antivirus tools in the system? Defender? They can block/slow gcc compiler checking each new object file and subprocess creating.

**Comment by MCUdude** [comment]
I'm using Windows defender, yes. I tried to turn off some of the security-related settings, and compile time dropped down to about 11 seconds.

I'm sure it's somehow related to my computer. I'll test on my 2015 Macbook Pro tonight.

**Comment by ivankravets** [comment]
Screen Shot 2019-08-20 at 13 17 23


Even in my VM 1 CPU which is very slow, WIndows 10, it took 10 sec.

Yes, it should be OS security related things. They can control GCC spawning and produced objects

**Comment by MCUdude** [comment]
My windows computer is quite fast. It's a Dell XPS 15 from 2016 with more-than-enough computing power to run GCC.

**Comment by ivankravets** [comment]
Could you run this in the terminal?
```
python -c "from multiprocessing import cpu_count;print(cpu_count())"
``

**Comment by MCUdude** [comment]
```
python -c "from multiprocessing import cpu_count;print(cpu_count())"
```
returns 8

**Comment by ivankravets** [comment]
Oh.. :) it should take 1-2secs :)

**Pull request closed without merging**
